name: Run crawler for reviews

on:
  schedule:
    # at minte 0 past every 24th hout
    - cron: '0 */24 * * *'
      #at every 5th minutes
    - cron: '*/5 * * * *'
      #*/5 * * * *
  workflow_dispatch:
jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python crawler/reviews.py

      - name: Commit and push changes
        if: steps.changed-files.outputs.files_changed == 'true'
        run: |
          git config user.name "jongseokleedev"
          git config user.email "jongsuklee45@gmail.com"
          git add .
          git commit -m "Update last_review_id.json"
          git push https://${{ secrets.GH_TOKEN }}@github.com/yeonjin1357/action_test.git