name: Run Crawler for Reviews

on:
  schedule:
    - cron: '50 * * * *'
  workflow_dispatch:
jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_reviews.txt

      - name: Run Python script
        env :
          APP_STORE_REVIEW_URL : ${{secrets.APP_STORE_REVIEW_URL}}
          SLACK_ALARMY_OAUTH_TOKEN : ${{secrets.SLACK_ALARMY_OAUTH_TOKEN}}
          SLACK_USER_VOICE_CHANNEL_ID : ${{secrets.SLACK_USER_VOICE_CHANNEL_ID}}
        run: python crawlers/reviews.py


      - name: Check for changes
        id: check_changes
        run: |
          git config user.name "${{ secrets.JACOB_GH_USER_NAME }}"
          git config user.email "${{ secrets.JACOB_EMAIL }}"
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes found"
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "no changes"
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "Update last_review_id.json"
          git push https://${{ secrets.JACOB_GH_TOKEN }}@github.com/goodnodes/syeong_slack_bot.git