name: Run Crawler for Ranking

on:
  schedule:
    - cron: '20 13 * * *'  # 12분마다 실행
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements_ranking.txt

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
        sudo apt-get install -y google-chrome-stable

    - name: Run Ranking Crawler
      env:
        APP_STORE_SYEONG_URL: ${{secrets.APP_STORE_SYEONG_URL}}
        SLACK_ALARMY_OAUTH_TOKEN: ${{secrets.SLACK_ALARMY_OAUTH_TOKEN}}
        SLACK_NOTIFICATIONS_CHANNEL_ID: ${{secrets.SLACK_NOTIFICATIONS_CHANNEL_ID}}
        JACOB_GH_USER_NAME: ${{secrets.JACOB_GH_USER_NAME}}
        JACOB_EMAIL: ${{secrets.JACOB_EMAIL}}
      run: python crawlers/ranking.py

    - name: Commit and push changes
      if: steps.changed-files.outputs.files_changed == 'true'
      run: |
        git config user.name "${{ secrets.JACOB_GH_USER_NAME }}"
        git config user.email "${{ secrets.JACOB_EMAIL }}"
        git add .
        git commit -m "Update data by workflows"
        git push https://${{ secrets.JACOB_GH_TOKEN }}@github.com/goodnodes/syeong_slack_bot.git